[tool.poetry]

name = "sydraw_dash_app"
version = "0.0.1"
description = ""
authors = ["William Bonvini"]
readme = "README.md"

[tool.poetry.dependencies]

python = ">=3.9.5, <3.12"

# Graphical Tools
plotly = "^5.13"
dash = "^2.8"
sydraw = "0.0.1"
gunicorn = "^20.1.0"
pandas = "^1.5.3"



